### ISSUE TITLE
MPI test hangs when worker process dies.

### ISSUE THREAD

**Issue by mloubout** [opesci/inversion#28]
@ggorman 
We need an MPI machine to test it, as I oly have a master so it doesn't run anything. But bug should be fixed

**Comment by ggorman** [comment]
1. You can run MPI on your laptop (ok - we have some cygwin issues for you to sort out - open this as a separate issue) or any workstation. You will just need to pip install mpi4py.

2. It probably runs too long for travis - but the first challenge is to get it running without actually crashing! 

3. The main issue with this test case currently is that if the worker dies, the whole progress does not fail - therefore we have to wait for a timeout if running this on travis. I am assuming this it the actual bug that needs to be fixed in this issue and will update the title to reflect this.

**Comment by mloubout** [comment]
@ggorman 

Here is the two main things me need to make

1. Velocity model extension. The model we read is the true model, we need to extend it for the PML layer (add nbpml in each direction and pad it with the boundary value)

2. Time interpolation. We need an operator that interpolates the time step axis (0:dt:(nt-1)*dt) to the shot axis (0:shotsample:length(shot))

less urgent but still

3. Receiver grid interpolation to have the correct number of samples and positional reads

4. Velocity model interpolation so that grid size is consistent with the source frequency
 

the fwi_mpi,py will definitely not run until the first two are fixed

**Comment by mloubout** [comment]
@ggorman 
Second message, because different topic

>You can run MPI on your laptop (ok - we have some cygwin issues for you to sort out - open this as a separate issue) or any workstation. You will just need to pip install mpi4py.

it's fine I have it working on my UBC mac, just need screenshare
